#!/bin/env ruby
#
# © Johannes Krude 2008
#
# This file is part of sendfile-utils.
#
# broadcast-files is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# broadcast-files is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
#

require 'socket'
require 'magicmime'
require 'io2io'

module SendHTTP

	def SendHTTP.do(file, filename, port)
		listen= TCPServer.new(nil, port)
		sockets= []
		threads= []
		begin
			while sockets<< listen.accept
				lock= true
				threads<< Thread.new do
					local= sockets[-1]
					lock= false
					data= ""
					begin
						data+= local.read_nonblock(1024*1024)
						if data=~ /\n/
							line= data.to_a[0].strip
							if line=~ /^GET \/(.*?) HTTP\/1.[01]$/ and $1==filename
								listen.close
								sockets.delete local
								sockets.each { |s| s.close }
								local.puts "HTTP/1.1 200 OK"
								local.puts "Server: sendfile-utils/#{$version}"
								local.puts "Content-Length: #{File.size file.path}" if File===file
								local.puts "Content-Type: #{MagicMime.file(file.path)}"
								local.puts "Connection: close"
								local.puts 
								begin
									IO2IO.forever(file.to_i, local.to_i)
								rescue Errno::EPIPE
									STDERR.puts "Upload aborted by client"
									exit 3
								rescue Errno::ECONNRESET
									STDERR.puts "Upload aborted by client"
									exit 3
								end
							else
								local.puts "HTTP/1.1 400 Bad Request"
								local.puts "Server: sendfile-utils/#{$version}"
								local.puts
							end
							local.close
							sockets.delete(local)
						end
					rescue Errno::EAGAIN
						retry
					rescue IOError
						sockets.delete(local)
					rescue EOFError
						local.close
						sockets.delete(local)
					end
				end
				sleep 0.01 while lock
			end
		rescue Errno::EAGAIN
			retry
		rescue IOError
			threads.each { |t| t.join }
		end
	end

end

$network_module= SendHTTP
load 'sendfile'
